---

plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  es2020: true
  jest: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  no-console: 0
  import/extensions: 0
  no-await-in-loop: 0
  "no-underscore-dangle": 'off'